### ISSUE TITLE
open inventory bug

### ISSUE THREAD

**Issue by ninjaloose** [mattsemar/dsp-long-arm#3]
Experiencing an issue with LongArm when opening the inventory by pressing the 'E' key anywhere. Disabling LongArm stops the error and it behaves as normal.
Below link to screenshot of the red message in game
https://steamcommunity.com/sharedfiles/filedetails/?id=2872304018

**Comment by ZL1LAC** [comment]
Can confirm I'm also getting this error.

**Comment by starfi5h** [comment]
Made a plugin to fix the issue. Install this can make LongArm run without this error.   
https://dsp.thunderstore.io/package/starfi5h/ModFixerOne/

What it does is replace `uigame.inventory` to `uigame.inventoryWindow` in this line
https://github.com/mattsemar/dsp-long-arm/blob/master/UI/LongArmUi.cs#L562

**Comment by ninjaloose** [comment]
Starfi5h you're the champion that we don't deserve, thanks for keeping Semar's hard work alive!

**Comment by newbienoobplayer** [comment]
Starfi5h u r a live saver
